stages:
  - build_symfony

variables:
  PHP_IMAGE: "php:7.4"
  MYSQL_IMAGE: "mysql:latest"
  MYSQL_ROOT_PASSWORD: "your-root-password"
  MYSQL_DATABASE: "your-database-name"
  MYSQL_USER: "your-mysql-user"
  MYSQL_PASSWORD: "your-mysql-password"


build_symfony:
  image: $PHP_IMAGE
  stage: build_symfony
  script:
    - apt-get update -y
    - apt-get install -y unzip  # Install unzip, which is needed for Composer
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - cd /builds/Suraif16/angular-crud-app2/server
    - composer install
    - php bin/console doctrine:database:create --if-not-exists
    - php bin/console doctrine:schema:update --force
    - php bin/console server:start &

