stages:
  - build_angular
  - build_symfony
  - run_cypress

variables:
  CYPRESS_IMAGE:  "cypress/browsers:node18.6.0-chrome105-ff104"
  PHP_IMAGE: "php:8.1"
  MYSQL_IMAGE: "mysql:latest"
  MYSQL_ROOT_PASSWORD: "your-root-password"
  MYSQL_DATABASE: "your-database-name"
  MYSQL_USER: "your-mysql-user"
  MYSQL_PASSWORD: "your-mysql-password"

  
build_symfony:
  image: $PHP_IMAGE
  stage: build_symfony
  script:
    - apt-get update -y
    - apt-get install -y unzip  # Install unzip, which is needed for Composer
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - cd /builds/Suraif16/angular-crud-app2/server
    - composer install
    - php bin/console server:start &

build_angular:
  image: $CYPRESS_IMAGE
  stage: build_angular
  script:
  # Start Angular app in the background
  - cd /builds/Suraif16/angular-crud-app2/client
  - npm ci
  - npm install -g @angular/cli 
  - npm install -g n
  - n 18.13.0  # Install Node.js v18.13
  - ng serve &
  - cd /builds/Suraif16/angular-crud-app2/cypress-automation-framework
  - npm ci
  - npm run runOnChrome &





