stages:
  - build_angular
  - build_symfony
  - run_cypress

variables:
  CYPRESS_IMAGE:  "cypress/browsers:node18.6.0-chrome105-ff104"
  PHP_IMAGE: "php:8.1"
  MYSQL_DATABASE: "angular"
  MYSQL_ROOT_PASSWORD: ""
  MYSQL_USER: "root"
  MYSQL_PASSWORD: ""
  MYSQL_HOST: mysql


  
build_symfony:
  image: $PHP_IMAGE
  stage: build_symfony
  services:
    - mysql:5.7
  script:
    - apt-get update -y
    - apt-get install -y unzip  # Install unzip, which is needed for Composer
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - cd /builds/Suraif16/angular-crud-app2/server
    - composer install
    - php bin/console server:start &

    # Installing MySQL here 
    - apt-get update && apt-get install -y git curl libmcrypt-dev default-mysql-client
    - mysql --version
    - sleep 20
    - echo "SHOW tables;" | mysql -u root -p"$MYSQL_ROOT_PASSWORD" -h "${MYSQL_HOST}" "${MYSQL_DATABASE}"
    - echo "Database host is '${MYSQL_HOST}'"


build_angular:
  image: $CYPRESS_IMAGE
  stage: build_angular
  script:
  # Start Angular app in the background
  - cd /builds/Suraif16/angular-crud-app2/client
  - npm ci
  - npm install -g @angular/cli 
  - npm install -g n
  - n 18.13.0  # Install Node.js v18.13
  - ng serve &


run_cypress:
  image: $CYPRESS_IMAGE
  stage: run_cypress
  script:
    - cd /builds/Suraif16/angular-crud-app2/cypress-automation-framework
    - npm ci
    - npm run runOnChrome &





