stages:
  - test

test:
  image: cypress/browsers:node18.6.0-chrome105-ff104 
  stage: test
  script:
    - "echo Present Working Directory: $(pwd)"

    # Start Angular app in the background
    - cd /builds/Suraif16/angular-crud-app2/client
    - npm ci
    - npm install -g @angular/cli 
    - npm install -g n
    - n 18.13.0  # Install Node.js v18.13
    - ng serve &

    # Run Cypress tests
    - cd /builds/Suraif16/angular-crud-app2/cypress-automation-framework
    - npm ci
    - npm run runOnChrome 
