stages:
  - test

test:  
    image: cypress/browsers:node18.6.0-chrome105-ff104 
    stage: test
    script:
      - "echo Present Working Directory: $(pwd)"
      - cd /builds/Suraif16/angular-crud-app2/client
      - npm install
      - ng serve  # Start Angular app in the background
      - cd /builds/Suraif16/angular-crud-app2/server
      - composer install
      - php  symfony server:start  # Start Symfony app in the background
      - cd /builds/Suraif16/angular-crud-app2/cypress-automation-framework
      - npm ci
      - npm test
