stages:
  - test

test:  
    image: cypress/browsers:node16.5.0-chrome94-ff93  
    stage: test
    script:
      - nvm install 20.9.0
      - nvm use 20.9.0
      - "echo Present Working Directory: $(pwd)"
      - cd /builds/Suraif16/angular-crud-app2/client
      - npm install
      - ng serve  # Start Angular app in the background
      - cd /builds/Suraif16/angular-crud-app2/server
      - composer install
      - php  symfony server:start  # Start Symfony app in the background
      - cd /builds/Suraif16/angular-crud-app2/cypress-automation-framework
      - npm ci
      - npm test
