stages:
  - test

test:
  image: cypress/browsers:node18.6.0-chrome105-ff104 
  stage: test
  script:
    - "echo Present Working Directory: $(pwd)"

    # Start Angular app in the background
    - cd /builds/Suraif16/angular-crud-app2/client
    - npm ci
    - npm install -g @angular/cli 
    - npm install -g n
    - n 18.13.0  # Install Node.js v18.13
    - ng serve &

    # Start Symfony app in the background
    - cd /builds/Suraif16/angular-crud-app2/server
    - apt-get update && apt-get install -y unzip  
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - composer install
    - composer install
    - php  symfony server:start &

    # # Wait for services to be ready (adjust sleep time as needed)
    # - sleep 20

    # Run Cypress tests
    - cd /builds/Suraif16/angular-crud-app2/cypress-automation-framework
    - npm ci
    - npm test
    
    
    

