stages:
  - build_symfony

variables:
  PHP_IMAGE: "php:7.4"
  MYSQL_IMAGE: "mysql:latest"
  MYSQL_ROOT_PASSWORD: "your-root-password"
  MYSQL_DATABASE: "your-database-name"
  MYSQL_USER: "your-mysql-user"
  MYSQL_PASSWORD: "your-mysql-password"


build_symfony:
  image: $PHP_IMAGE
  stage: build_symfony
  script:
    - cd /builds/Suraif16/angular-crud-app2/server
    - composer install
    # Assuming Symfony app uses Doctrine, update database schema
    - php bin/console doctrine:database:create --if-not-exists
    - php bin/console doctrine:schema:update --force
    # Add any additional Symfony build commands here
    - php bin/console server:start &

